### ISSUE TITLE
libfdk-aac.so.1 in /usr/local/lib not found

### ISSUE THREAD

**Issue by zjons** [nu774/fdkaac#17]
A minor annoyance when installing on fedoa 21.
ligbdk-aac.so is installed in /usr/local/lib by default.  After compiling and installing fdkaac I got the message "error while loading shared libraries: libfdk-aac.so.1: cannot open shared object file: No such file or directory".
Symlinking the libraries in /usr/lib64/ solved the problem.
I don't remember having this problem before.  Shouldn't the config script figure this out?

**Comment by nu774** [comment]
No.
Simply, you have installed your shared library (libfdk-aac.so) to the location where your system doesn't search by default.
If you want to use shared libraries under /usr/local/lib but your system loader doesn't search them,  you have to manually set LD_LIBRARY_PATH or edit /etc/ld.so.conf.

**Comment by MaxDeepCoder** [comment]
What do I edit it as?
My ld.so.conf is

include /etc/ld.so.conf.d/*.conf
