### ISSUE TITLE
Can't compile under visual studio 2015

### ISSUE THREAD

**Issue by ssc19940105** [nu774/fdkaac#18]
Two errors:
Item severity code file line
Error LNK2019 unresolved external symbol ___wgetmainargs, the symbol is referenced in function _aacenc_getmainargs in fdkaac C : \ Users \ Shen Shu super \ Download \ compression \ fdkaac \ MSVC \ compat_win32.obj 1

Item severity code file line
Error LNK1120 1 which could not resolve the external command fdkaac C: \ Users \ Shen Shu super \ Downloads \ Compressed \ fdkaac \ MSVC \ Debug \ fdkaac.exe 1

**Comment by nu774** [comment]
Thx for reporting.
Fixed on e403976bf6e3d7c9a487c8be3918f74dca7af1b9
