### ISSUE TITLE
fdkaac-0.6.3 build error

### ISSUE THREAD

**Issue by MegaMcVolt** [nu774/fdkaac#26]
OS - Slackware 14.2 (Linux 4.4.38 (x86_64))
Desktop environment - XFCE 4
libfdk-aac - 0.1.5

The part where the errors occurred when compiling:
-----------------------------------------------------------------
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:12: installing './compile'
configure.ac:41: installing './config.guess'
configure.ac:41: installing './config.sub'
configure.ac:10: installing './install-sh'
configure.ac:10: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking localcharset.h usability... yes
checking localcharset.h presence... yes
checking for localcharset.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking fdk-aac/aacenc_lib.h usability... yes
checking fdk-aac/aacenc_lib.h presence... yes
checking for fdk-aac/aacenc_lib.h... yes
checking for inline... inline
checking whether byte ordering is bigendian... no
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for ptrdiff_t... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for struct __timeb64... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for sigaction... yes
checking for gettimeofday... yes
checking for nl_langinfo... yes
checking for _vscprintf... no
checking for fseeko64... yes
checking for getopt_long... yes
checking for library containing aacEncOpen... -lfdk-aac
checking build system type... x86_64-slackware-linux-gnu
checking host system type... x86_64-slackware-linux-gnu
checking for ld used by gcc... /usr/x86_64-slackware-linux/bin/ld
checking if the linker (/usr/x86_64-slackware-linux/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
configure: WARNING: unrecognized options: --enable-unicode
make  all-am
make[1]: вход в каталог «/tmp/build/multimedia/fdkaac/fdkaac-0.6.3»
depbase=`echo src/aacenc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/aacenc.o -MD -MP -MF $depbase.Tpo -c -o src/aacenc.o src/aacenc.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/caf_reader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/caf_reader.o -MD -MP -MF $depbase.Tpo -c -o src/caf_reader.o src/caf_reader.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/extrapolater.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/extrapolater.o -MD -MP -MF $depbase.Tpo -c -o src/extrapolater.o src/extrapolater.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/limiter.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/limiter.o -MD -MP -MF $depbase.Tpo -c -o src/limiter.o src/limiter.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/lpc.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/lpc.o -MD -MP -MF $depbase.Tpo -c -o src/lpc.o src/lpc.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/m4af.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/m4af.o -MD -MP -MF $depbase.Tpo -c -o src/m4af.o src/m4af.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/main.o -MD -MP -MF $depbase.Tpo -c -o src/main.o src/main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/metadata.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/metadata.o -MD -MP -MF $depbase.Tpo -c -o src/metadata.o src/metadata.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/parson.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/parson.o -MD -MP -MF $depbase.Tpo -c -o src/parson.o src/parson.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/pcm_float_converter.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/pcm_float_converter.o -MD -MP -MF $depbase.Tpo -c -o src/pcm_float_converter.o src/pcm_float_converter.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/pcm_native_converter.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/pcm_native_converter.o -MD -MP -MF $depbase.Tpo -c -o src/pcm_native_converter.o src/pcm_native_converter.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/pcm_readhelper.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/pcm_readhelper.o -MD -MP -MF $depbase.Tpo -c -o src/pcm_readhelper.o src/pcm_readhelper.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/pcm_sint16_converter.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/pcm_sint16_converter.o -MD -MP -MF $depbase.Tpo -c -o src/pcm_sint16_converter.o src/pcm_sint16_converter.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/progress.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/progress.o -MD -MP -MF $depbase.Tpo -c -o src/progress.o src/progress.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/wav_reader.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/wav_reader.o -MD -MP -MF $depbase.Tpo -c -o src/wav_reader.o src/wav_reader.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo src/compat_posix.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -O2 -fPIC -MT src/compat_posix.o -MD -MP -MF $depbase.Tpo -c -o src/compat_posix.o src/compat_posix.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc  -O2 -fPIC   -o fdkaac src/aacenc.o src/caf_reader.o src/extrapolater.o src/limiter.o src/lpc.o src/m4af.o src/main.o src/metadata.o src/parson.o src/pcm_float_converter.o src/pcm_native_converter.o src/pcm_readhelper.o src/pcm_sint16_converter.o src/progress.o src/wav_reader.o src/compat_posix.o   -lfdk-aac -lm -lfdk-aac 
src/compat_posix.o: In function `aacenc_to_utf8':
compat_posix.c:(.text+0xe7): undefined reference to `locale_charset'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[1]: *** [Makefile:511: fdkaac] Ошибка 1
make[1]: выход из каталога «/tmp/build/multimedia/fdkaac/fdkaac-0.6.3»
make: *** [Makefile:369: all] Ошибка 2

**Comment by nu774** [comment]
Can you try with the latest commit https://github.com/nu774/fdkaac/commit/4682fe4961b92d3872e47d9fd4d9256151d292e7 ?

**Comment by MegaMcVolt** [comment]
Thank you so much!
I have everything compiled!
Thank you for your quick response to my problem. Long life to you, and good health!
Sorry for my English...
