### ISSUE TITLE
Is it possible to pipe from ogg123?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nu774/fdkaac#28]
I tried

`ogg123 in.ogg - | fdkaac -b128 - -o out.m4a`

And I see

`ERROR: unsupported input file`

**Comment by nu774** [comment]
Are you sure that your usage of ogg123 command is correct?
I think you need something like the following:
<pre>ogg123 -d wav in.ogg -f - | fdkaac -b128 - -o out.m4a</pre>

**Comment by vitaly-zdanevich** [comment]
Thank you!

**Comment by vitaly-zdanevich** [comment]
Maybe you know - is it possible to feed file to the ogg123 from Python - when byte stream in ram? Or maybe there is some other way I can convert ogg vorbis from memory to the m4a/aac?

**Comment by vitaly-zdanevich** [comment]
I found https://stackoverflow.com/questions/46789568/python-how-to-write-binary-data-to-the-stdout-so-that-bash-script-can-use-proce
