### ISSUE TITLE
Is it possible to pipe from?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nu774/fdkaac#29]
I tried

`ogg123 -d wav file.ogg -f - | fdkaac -m5 - -o - | cat`

And see no output.

**Comment by nu774** [comment]
Well, didn't you?
I can clearly see the output (error message) from fdkaac which says that "stdout streaming is not available on M4A output".

fdkaac chooses M4A container by default (which can be changed by -f option), and as the error message says, output to stdout is not supported on M4A.
This is also written in "DESCRIPTION" section in man mage.

**Comment by vitaly-zdanevich** [comment]
Oh, thank you...

Output to stdout is not possible for m4a due to some format restrictions or it may be implemented in the future?

**Comment by nu774** [comment]
Normal MP4 format is just not suitable for piped output.

**Comment by vitaly-zdanevich** [comment]
Ok, thank you.
