### ISSUE TITLE
Question:  is there a way to add delay ( padding )

### ISSUE THREAD

**Issue by mofortin** [nu774/fdkaac#33]
Hi,

I would like to know if there is a way to add delay when encoding ? The same way you can with your implementation of QAAC with --delay

thanks.

**Comment by nu774** [comment]
No.
As you can see in the man page or help message, there's no such option.
As far as I know, other popular encoders such as lame, oggenc, opusenc, neroaacenc also don't implement such an option, so I think it's basically unnecessary.
qaac is an abnormally versatile command line encoder but I want to keep fdkaac simple.

**Comment by mofortin** [comment]
Aight.. Thanks anyway for the quick answer :)
