### ISSUE TITLE
Please add into README - how to deal with ' in title

### ISSUE THREAD

**Issue by vitaly-zdanevich** [nu774/fdkaac#38]
For example now I have this Python code:

    title_escaped = title.replace("'", r"'\''")

    cmd = fr'''cd /tmp;
            curl {urls} |
            /var/task/oggdec - -o - |
            /var/task/fdkaac -m5 - -o "{episode_filename}"
         --title='{title_escaped}'
         --artist='Intelligent Speaker'
         --album-artist='Intelligent Speaker'
         --album='Intelligent Speaker'
         --genre='Podcast'
         --date='{pubDate}'
         --comment='Voiced text from {source}'
        '''.replace('\n', '')
    output_from_shell = subprocess.getoutput(cmd)

But if `title` with single quote - I get error

> /bin/sh: -c: line 0: unexpected EOF while looking for matching `''

**Comment by nu774** [comment]
```/bin/sh: -c: line 0: unexpected EOF while looking for matching `''```
This error message is apparently from the shell (/bin/sh) . In other word you have to learn how to correctly quote/escape arguments for the shell.
It has nothing to do with fdkaac.
