### ISSUE TITLE
Reading from stdin on Windows 10 seems to be broken

### ISSUE THREAD

**Issue by GOATS2K** [nu774/fdkaac#44]
Hey!

I attempted to run the following command in Powershell:

`.\flac.exe 'in.flac' -s -d -c | .\fdkaac.exe - --ignorelength --bitrate 192 -w 20000 -o test.m4a`

Which resulted in the following error message:

`ERROR: unsupported input file`

What's strange is that the same exact command worked fine in Ubuntu 20.04.

Do you have any idea on where we can begin debugging this?

Edit: Actually, running the command in Command Prompt works just fine - it's just very slow.

**Comment by nu774** [comment]
You just cannot pipe binary data in powershell:
https://stackoverflow.com/questions/54086430/how-to-pipe-binary-data-in-powershell

**Comment by GOATS2K** [comment]
Ah, that's unfortunate. Thanks for your help!
