### ISSUE TITLE
Debian packaging wanted?

### ISSUE THREAD

**Issue by rbrito** [nu774/fdkaac#8]
Hi there.

As I mentioned briefly some time ago in hydrogenaudio, I was/am working on the Debian packaging of fdkaac, so that the executable can be produced in an automated way.

Do you want me to send a pull request with what I have so far? My idea would be to merge it in a, perhaps, separate branch, unless you don't mind it being in the master branch.

Thanks,

Rogério.

**Comment by calestyo** [comment]
There's now a official Debian package waiting for being accepted in the new queue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766679

**Comment by jrnewell** [comment]
Kind of off topic, but there is also an OS X homebrew formula for this too: ``fdk-aac-encoder``
